//
//  NCMConversionRegistry.swift
//  kmgccc_player
//

import Foundation

// NCMConversionAssociation is persisted with TrackSidecar in LibrarySidecars.swift.

nonisolated enum NCMConversionState: String, Codable, Sendable {
    case pending
    case outputReady
    case committed
    case removed
    case failed
}

nonisolated struct NCMConversionRecord: Codable, Sendable, Identifiable {
    let id: UUID
    let sourceIdentity: ReferencedFileIdentity?
    let sourceFingerprint: ReferencedFileFingerprint
    let sourceBookmarkData: Data
    let parentDirectoryBookmarkData: Data?
    let sourcePath: String
    let sourceMemberships: [ReferencedSourceMembership]
    let sourcePrimaryID: UUID?
    let expectedOutputPath: String
    var outputIdentity: ReferencedFileIdentity?
    var outputFingerprint: ReferencedFileFingerprint?
    var outputLocator: ReferencedFileLocator?
    var outputFormat: NCMFormat?
    var outputMetadata: NCMMetadata?
    var outputCoverData: Data?
    var trackID: UUID?
    var state: NCMConversionState
    var errorSummary: String?
    /// Process-unique tag of the run that created this reservation. Absent on
    /// journals written before this field existed; treated as a foreign
    /// process so legacy crash debris still recovers.
    var creatorProcessEpoch: String?
    let createdAt: Date
    var updatedAt: Date
}

/// A small source-folder marker for products generated by this app. The
/// journal belongs to the music library, while this marker travels with the
/// user's source folder and lets a newly-created library recognize an older
/// conversion without re-decoding the NCM audio.
nonisolated struct NCMGeneratedOutputRecord: Codable, Sendable {
    let operationID: UUID
    let sourcePath: String
    let sourceFingerprint: ReferencedFileFingerprint
    let outputPath: String
    let outputFingerprint: ReferencedFileFingerprint
    let format: NCMFormat
    let metadata: NCMMetadata
    let createdAt: Date
    var updatedAt: Date
}

nonisolated struct NCMGeneratedOutputMarkerFile: Codable, Sendable {
    static let currentSchemaVersion = 1

    var schemaVersion = Self.currentSchemaVersion
    var records: [NCMGeneratedOutputRecord] = []
}

/// File-based helpers are intentionally synchronous and stateless. Callers
/// already serialize imports on the main actor or inside the source scanner;
/// each write is atomic so a crash cannot leave a half-written marker.
nonisolated enum NCMGeneratedOutputMarkerStore {
    static let fileName = ".kmgccc-ncm-conversions.json"

    static func load(
        in outputDirectory: URL,
        fileManager: FileManager = .default
    ) throws -> NCMGeneratedOutputMarkerFile {
        let url = markerURL(in: outputDirectory)
        guard fileManager.fileExists(atPath: url.path) else {
            return NCMGeneratedOutputMarkerFile()
        }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let file = try decoder.decode(
            NCMGeneratedOutputMarkerFile.self,
            from: Data(contentsOf: url)
        )
        guard file.schemaVersion == NCMGeneratedOutputMarkerFile.currentSchemaVersion else {
            throw NCMConversionRegistryError.unsupportedSchema(file.schemaVersion)
        }
        return file
    }

    static func upsert(
        _ record: NCMGeneratedOutputRecord,
        in outputDirectory: URL,
        fileManager: FileManager = .default
    ) throws {
        try fileManager.createDirectory(at: outputDirectory, withIntermediateDirectories: true)
        var file: NCMGeneratedOutputMarkerFile
        do {
            file = try load(in: outputDirectory, fileManager: fileManager)
        } catch {
            // A corrupt marker must not make a valid source folder
            // permanently unimportable. The next successful atomic write
            // replaces only this metadata file; audio products are untouched.
            file = NCMGeneratedOutputMarkerFile()
        }
        if let index = file.records.firstIndex(where: {
            $0.operationID == record.operationID
                || sameExactFingerprint($0.sourceFingerprint, record.sourceFingerprint)
        }) {
            file.records[index] = record
        } else {
            file.records.append(record)
        }
        file.records.sort { $0.updatedAt < $1.updatedAt }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        try encoder.encode(file).write(to: markerURL(in: outputDirectory), options: .atomic)
    }

    /// Finds a valid product for the exact current NCM file. The source
    /// fingerprint check prevents a changed-in-place NCM from silently
    /// reusing an old product with the same title.
    static func reusableRecord(
        for _: URL,
        sourceFingerprint: ReferencedFileFingerprint,
        in outputDirectory: URL,
        fileManager: FileManager = .default,
        identityProvider: ReferencedFileIdentityProvider = .init()
    ) -> (record: NCMGeneratedOutputRecord, outputURL: URL)? {
        guard let file = try? load(in: outputDirectory, fileManager: fileManager) else { return nil }
        for record in file.records where sameExactFingerprint(record.sourceFingerprint, sourceFingerprint) {
            guard let outputURL = existingOutputURL(
                for: record,
                in: outputDirectory,
                fileManager: fileManager
            ),
            let actual = try? identityProvider.fingerprint(for: outputURL),
            sameExactFingerprint(record.outputFingerprint, actual) else { continue }
            return (record, outputURL)
        }
        return nil
    }

    /// Source scanning uses this to hide generated products while their NCM
    /// input remains the canonical manifest entry. A user can still import the
    /// visible MP3 directly by selecting that file instead of its folder.
    static func isGeneratedOutput(
        _ outputURL: URL,
        fingerprint: ReferencedFileFingerprint,
        fileManager: FileManager = .default
    ) -> Bool {
        guard let file = try? load(
            in: outputURL.deletingLastPathComponent(),
            fileManager: fileManager
        ) else { return false }
        return file.records.contains { record in
            let pathMatches = canonicalPath(record.outputPath) == canonicalPath(outputURL.path)
            return pathMatches && sameExactFingerprint(record.outputFingerprint, fingerprint)
        }
    }

    static func record(
        forOutputPath outputURL: URL,
        fileManager: FileManager = .default
    ) -> NCMGeneratedOutputRecord? {
        guard let file = try? load(
            in: outputURL.deletingLastPathComponent(),
            fileManager: fileManager
        ) else { return nil }
        let path = canonicalPath(outputURL.path)
        return file.records.first { canonicalPath($0.outputPath) == path }
    }

    static func sameExactFingerprint(
        _ lhs: ReferencedFileFingerprint,
        _ rhs: ReferencedFileFingerprint
    ) -> Bool {
        TrackIdentityResolver.sameExactFingerprint(lhs, rhs)
    }

    private static func markerURL(in outputDirectory: URL) -> URL {
        outputDirectory.appendingPathComponent(fileName, isDirectory: false)
    }

    private static func existingOutputURL(
        for record: NCMGeneratedOutputRecord,
        in outputDirectory: URL,
        fileManager: FileManager
    ) -> URL? {
        let requested = URL(fileURLWithPath: record.outputPath).standardizedFileURL
        if fileManager.fileExists(atPath: requested.path) { return requested }
        guard let children = try? fileManager.contentsOfDirectory(
            at: outputDirectory,
            includingPropertiesForKeys: [.isRegularFileKey],
            options: [.skipsHiddenFiles]
        ) else { return nil }
        return children.first { child in
            guard (try? child.resourceValues(forKeys: [.isRegularFileKey]).isRegularFile) == true,
                  let fingerprint = try? ReferencedFileIdentityProvider().fingerprint(for: child) else {
                return false
            }
            return sameExactFingerprint(record.outputFingerprint, fingerprint)
        }
    }

    private static func canonicalPath(_ path: String) -> String {
        URL(fileURLWithPath: path).resolvingSymlinksInPath().standardizedFileURL.path
    }
}

nonisolated struct NCMConversionJournal: Codable, Sendable {
    static let currentSchemaVersion = 1
    var schemaVersion = Self.currentSchemaVersion
    var records: [NCMConversionRecord] = []
}

nonisolated enum NCMConversionRegistryError: Error, LocalizedError, Equatable {
    case unsupportedSchema(Int)
    case sourceAlreadyReserved(UUID)
    case outputAlreadyReserved(UUID)
    case recordNotFound(UUID)
    case invalidTransition

    var errorDescription: String? {
        switch self {
        case .unsupportedSchema(let version): return "Unsupported NCM conversion journal schema: \(version)"
        case .sourceAlreadyReserved: return "This NCM file already has an active conversion."
        case .outputAlreadyReserved: return "The NCM output is already reserved."
        case .recordNotFound: return "The NCM conversion reservation was not found."
        case .invalidTransition: return "The NCM conversion reservation is in an invalid state."
        }
    }
}

actor NCMConversionRegistry {
    private let url: URL
    private let fileManager = FileManager.default
    private var journal: NCMConversionJournal?
    private var stalePendingRecoveryIDs: [UUID] = []

    init(paths: LibraryPaths) {
        self.url = paths.ncmConversionsURL
    }

    func load() throws -> NCMConversionJournal {
        if let journal { return journal }
        guard fileManager.fileExists(atPath: url.path) else {
            let empty = NCMConversionJournal()
            journal = empty
            stalePendingRecoveryIDs = []
            return empty
        }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        var decoded = try decoder.decode(
            NCMConversionJournal.self,
            from: Data(contentsOf: url)
        )
        guard decoded.schemaVersion == NCMConversionJournal.currentSchemaVersion else {
            throw NCMConversionRegistryError.unsupportedSchema(decoded.schemaVersion)
        }
        // Opening the journal only retires reservations from OTHER processes:
        // conversions never outlive the session that started them, but sibling
        // registry instances in THIS process legitimately share live `.pending`
        // records (scanner filter + conversion service). Records are stamped
        // with a per-process epoch at reserve() time; anything carrying a
        // different or missing epoch is crash debris. Without this gate, a
        // crash between reserve() and markOutputReady would block the source
        // forever.
        let recovered = Self.retireStalePendingRecords(&decoded, fileManager: fileManager)
        stalePendingRecoveryIDs = recovered
        if recovered.isEmpty {
            journal = decoded
        } else {
            // Best effort: an unwritable journal must not brick every
            // registry operation. The healed in-memory copy reaches disk on
            // the next successful persist, and recovery itself is idempotent.
            try? persist(decoded)
        }
        return decoded
    }

    /// Retires reservations left `.pending` by a previous process and returns
    /// their operation IDs. A no-op once this instance has loaded the journal.
    @discardableResult
    func recoverStalePendingReservations() throws -> [UUID] {
        _ = try load()
        return stalePendingRecoveryIDs
    }

    /// Conversions are strictly in-process, so a `.pending` record stamped by
    /// another process (or written before stamping existed) that survived
    /// until the journal was reopened is crash debris. It is retired to
    /// `.failed` — the same recoverable state used when output-ready
    /// recovery finds its product missing — which blocks nothing: not
    /// `reserve`, not `activeRecord`, not `isReserved`.
    nonisolated private static func retireStalePendingRecords(
        _ journal: inout NCMConversionJournal,
        fileManager: FileManager
    ) -> [UUID] {
        var retired: [UUID] = []
        for index in journal.records.indices
        where journal.records[index].state == .pending
            && journal.records[index].creatorProcessEpoch != creatorProcessEpoch {
            removeCrashDebris(for: journal.records[index], fileManager: fileManager)
            journal.records[index].state = .failed
            journal.records[index].errorSummary =
                "App exited before the conversion finished; reservation recovered"
            journal.records[index].updatedAt = Date()
            retired.append(journal.records[index].id)
        }
        return retired
    }

    /// Removes the scratch artifacts a killed conversion leaves beside its
    /// NCM source: the temporary decode directory and the reservation
    /// placeholder, both named with the dead operation's UUID. A finalized
    /// output path (inside the managed "NCM 转换" folder) is deliberately left
    /// alone — it is either absent or a fully published product that the
    /// normal reuse path adopts on the next conversion.
    nonisolated private static func removeCrashDebris(
        for record: NCMConversionRecord,
        fileManager: FileManager
    ) {
        let sourceParent = URL(fileURLWithPath: record.sourcePath).deletingLastPathComponent()
        let temporaryDirectory = sourceParent
            .appendingPathComponent(".kmgccc-ncm-\(record.id.uuidString)", isDirectory: true)
        try? fileManager.removeItem(at: temporaryDirectory)
        let placeholder = sourceParent
            .appendingPathComponent(".kmgccc-ncm-\(record.id.uuidString).pending", isDirectory: false)
        let expectedOutput = URL(fileURLWithPath: record.expectedOutputPath).standardizedFileURL.path
        guard expectedOutput == placeholder.standardizedFileURL.path else { return }
        try? fileManager.removeItem(at: placeholder)
    }

    func reserve(_ record: NCMConversionRecord) throws {
        var current = try load()
        if let existing = current.records.first(where: {
            Self.sameSource($0, record)
                && ($0.state == .pending || $0.state == .outputReady || $0.state == .committed)
        }) {
            throw NCMConversionRegistryError.sourceAlreadyReserved(existing.id)
        }
        if let existing = current.records.first(where: {
            $0.expectedOutputPath == record.expectedOutputPath
                && ($0.state == .pending || $0.state == .outputReady || $0.state == .committed)
        }) {
            throw NCMConversionRegistryError.outputAlreadyReserved(existing.id)
        }
        var stamped = record
        if stamped.creatorProcessEpoch == nil {
            stamped.creatorProcessEpoch = Self.creatorProcessEpoch
        }
        current.records.append(stamped)
        try persist(current)
    }

    /// Process-unique tag written into every reservation this run creates.
    /// Load-time recovery only retires `.pending` records carrying a
    /// different (or missing) epoch, so sibling registry instances within one
    /// process — scanner reservation filter and conversion service — never
    /// invalidate each other's live reservations.
    nonisolated static let creatorProcessEpoch = UUID().uuidString

    func updateExpectedOutput(operationID: UUID, path: String) throws {
        var current = try load()
        guard let index = current.records.firstIndex(where: { $0.id == operationID }) else {
            throw NCMConversionRegistryError.recordNotFound(operationID)
        }
        guard current.records[index].state == .pending else {
            throw NCMConversionRegistryError.invalidTransition
        }
        if let existing = current.records.first(where: {
            $0.id != operationID && $0.expectedOutputPath == path && $0.state != .failed
        }) {
            throw NCMConversionRegistryError.outputAlreadyReserved(existing.id)
        }
        current.records[index] = NCMConversionRecord(
            id: current.records[index].id,
            sourceIdentity: current.records[index].sourceIdentity,
            sourceFingerprint: current.records[index].sourceFingerprint,
            sourceBookmarkData: current.records[index].sourceBookmarkData,
            parentDirectoryBookmarkData: current.records[index].parentDirectoryBookmarkData,
            sourcePath: current.records[index].sourcePath,
            sourceMemberships: current.records[index].sourceMemberships,
            sourcePrimaryID: current.records[index].sourcePrimaryID,
            expectedOutputPath: path,
            outputIdentity: current.records[index].outputIdentity,
            outputFingerprint: current.records[index].outputFingerprint,
            outputLocator: current.records[index].outputLocator,
            outputFormat: current.records[index].outputFormat,
            outputMetadata: current.records[index].outputMetadata,
            outputCoverData: current.records[index].outputCoverData,
            trackID: current.records[index].trackID,
            state: current.records[index].state,
            errorSummary: current.records[index].errorSummary,
            creatorProcessEpoch: current.records[index].creatorProcessEpoch,
            createdAt: current.records[index].createdAt,
            updatedAt: Date()
        )
        try persist(current)
    }

    func prepareOutputPayload(
        operationID: UUID,
        format: NCMFormat,
        metadata: NCMMetadata,
        coverData: Data?
    ) throws {
        try update(operationID) { record in
            guard record.state == .pending else { throw NCMConversionRegistryError.invalidTransition }
            record.outputFormat = format
            record.outputMetadata = metadata
            record.outputCoverData = coverData
            record.updatedAt = Date()
        }
    }

    func markOutputReady(
        operationID: UUID,
        outputFingerprint: ReferencedFileFingerprint,
        locator: ReferencedFileLocator,
        format: NCMFormat,
        metadata: NCMMetadata,
        coverData: Data?
    ) throws {
        try update(operationID) { record in
            guard record.state == .pending else { throw NCMConversionRegistryError.invalidTransition }
            record.outputFingerprint = outputFingerprint
            record.outputIdentity = outputFingerprint.identity
            record.outputLocator = locator
            record.outputFormat = format
            record.outputMetadata = metadata
            record.outputCoverData = coverData
            record.state = .outputReady
            record.updatedAt = Date()
        }
    }

    func associateTrack(operationID: UUID, trackID: UUID) throws {
        try update(operationID) { record in
            guard record.state == .outputReady else { throw NCMConversionRegistryError.invalidTransition }
            if let existing = record.trackID, existing != trackID {
                throw NCMConversionRegistryError.invalidTransition
            }
            record.trackID = trackID
            record.updatedAt = Date()
        }
    }

    func markCommitted(operationID: UUID, trackID: UUID) throws {
        try update(operationID) { record in
            guard record.state == .outputReady || record.state == .committed else {
                throw NCMConversionRegistryError.invalidTransition
            }
            record.trackID = trackID
            record.state = .committed
            record.errorSummary = nil
            record.updatedAt = Date()
        }
    }

    func markFailed(operationID: UUID, summary: String) throws {
        try update(operationID) { record in
            guard record.state != .committed && record.state != .removed else {
                throw NCMConversionRegistryError.invalidTransition
            }
            record.state = .failed
            record.errorSummary = String(summary.prefix(512))
            record.updatedAt = Date()
        }
    }

    func record(operationID: UUID) throws -> NCMConversionRecord? {
        try load().records.first { $0.id == operationID }
    }

    func updateOutputLocator(
        operationID: UUID,
        locator: ReferencedFileLocator
    ) throws {
        try update(operationID) { record in
            guard record.state == .outputReady || record.state == .committed else {
                throw NCMConversionRegistryError.invalidTransition
            }
            record.outputLocator = locator
            record.outputIdentity = locator.fingerprint?.identity
            record.outputFingerprint = locator.fingerprint
            record.updatedAt = Date()
        }
    }

    func committedRecord(matching fingerprint: ReferencedFileFingerprint) throws -> NCMConversionRecord? {
        try load().records.first {
            $0.state == .committed && Self.sameFingerprint($0.sourceFingerprint, fingerprint)
        }
    }

    func removedRecord(matching fingerprint: ReferencedFileFingerprint) throws -> NCMConversionRecord? {
        try load().records.first {
            $0.state == .removed && Self.sameFingerprint($0.sourceFingerprint, fingerprint)
        }
    }

    @discardableResult
    func markRemoved(operationID: UUID) throws -> NCMConversionRecord {
        var removed: NCMConversionRecord?
        try update(operationID) { record in
            guard record.state == .committed || record.state == .outputReady || record.state == .removed else {
                throw NCMConversionRegistryError.invalidTransition
            }
            record.state = .removed
            record.errorSummary = nil
            record.updatedAt = Date()
            removed = record
        }
        guard let removed else { throw NCMConversionRegistryError.recordNotFound(operationID) }
        return removed
    }

    func allowManualRetry(
        matching fingerprint: ReferencedFileFingerprint
    ) throws -> [ReferencedFileFingerprint] {
        var current = try load()
        // Stale `.pending` reservations are normally retired when the journal
        // loads; matching them here too lets a manual re-import force-clear
        // even a reservation this process is currently stuck on.
        guard let index = current.records.firstIndex(where: {
            ($0.state == .removed || $0.state == .pending)
                && Self.sameFingerprint($0.sourceFingerprint, fingerprint)
        }) else { return [] }
        var clearedFingerprints = [current.records[index].sourceFingerprint]
        if let outputFingerprint = current.records[index].outputFingerprint {
            clearedFingerprints.append(outputFingerprint)
        }
        let outputExists = fileManager.fileExists(atPath: current.records[index].expectedOutputPath)
        if outputExists,
           current.records[index].outputFingerprint != nil,
           current.records[index].outputFormat != nil,
           current.records[index].outputMetadata != nil {
            current.records[index].state = .outputReady
            current.records[index].trackID = nil
            current.records[index].errorSummary = nil
        } else {
            current.records[index].state = .failed
            current.records[index].trackID = nil
            current.records[index].errorSummary = "Manual retry requested"
        }
        current.records[index].updatedAt = Date()
        try persist(current)
        return clearedFingerprints
    }

    func restoreAfterFailedRemoval(operationID: UUID) throws {
        try update(operationID) { record in
            guard record.state == .removed else { return }
            record.state = record.trackID == nil ? .outputReady : .committed
            record.updatedAt = Date()
        }
    }

    func activeRecord(matching fingerprint: ReferencedFileFingerprint) throws -> NCMConversionRecord? {
        try load().records.first {
            ($0.state == .pending || $0.state == .outputReady)
                && Self.sameFingerprint($0.sourceFingerprint, fingerprint)
        }
    }

    func isReserved(url candidate: URL, identity: ReferencedFileIdentity?) throws -> Bool {
        let path = candidate.standardizedFileURL.path
        return try load().records.contains { record in
            switch record.state {
            case .pending, .outputReady:
                if let identity, identity == record.sourceIdentity || identity == record.outputIdentity {
                    return true
                }
                return record.sourcePath == path || record.expectedOutputPath == path
            case .committed:
                // Once the transaction is committed, keep the NCM source in
                // the source manifest. It is the canonical entry that lets a
                // folder scan survive while the generated output is hidden
                // by its source-folder marker.
                return false
            case .removed:
                if let identity, identity == record.sourceIdentity || identity == record.outputIdentity {
                    return true
                }
                return record.sourcePath == path || record.expectedOutputPath == path
            case .failed:
                return false
            }
        }
    }

    private func update(
        _ operationID: UUID,
        mutation: (inout NCMConversionRecord) throws -> Void
    ) throws {
        var current = try load()
        guard let index = current.records.firstIndex(where: { $0.id == operationID }) else {
            throw NCMConversionRegistryError.recordNotFound(operationID)
        }
        try mutation(&current.records[index])
        try persist(current)
    }

    private func persist(_ value: NCMConversionJournal) throws {
        try fileManager.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(value)
        let temporaryURL = url.deletingLastPathComponent()
            .appendingPathComponent(".\(url.lastPathComponent).\(UUID().uuidString).tmp")
        try data.write(to: temporaryURL, options: .atomic)
        if fileManager.fileExists(atPath: url.path) {
            _ = try fileManager.replaceItemAt(url, withItemAt: temporaryURL)
        } else {
            try fileManager.moveItem(at: temporaryURL, to: url)
        }
        journal = value
    }

    private static func sameSource(_ lhs: NCMConversionRecord, _ rhs: NCMConversionRecord) -> Bool {
        sameFingerprint(lhs.sourceFingerprint, rhs.sourceFingerprint)
    }

    nonisolated static func sameFingerprint(
        _ lhs: ReferencedFileFingerprint,
        _ rhs: ReferencedFileFingerprint
    ) -> Bool {
        TrackIdentityResolver.sameExactFingerprint(lhs, rhs)
    }
}
