#!/Users/kmg/Documents/vscode/player/myPlayer2/LDDC_Fetch_Core/.venv_arm64/bin/python3
import sys
from macholib.macho_dump import main
if __name__ == '__main__':
    sys.argv[0] = sys.argv[0].removesuffix('.exe')
    sys.exit(main())
